[package]
name = "cms-wikium"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.8"
prost = "0.11"
tokio = { version = "1", features = ["full"] }
futures = "0.3"

[build-dependencies]
tonic-build = "0.8"
