name: conquest-cms

services:
  go_server:
    build: .
    env_file:
      - .env
    # environment:
    #   # Pass the MONGO_URI from your host machine into the container
    #   - MONGO_URI=${MONGO_URI:-}
    networks:
      - grpc_net

  envoy:
    image: envoyproxy/envoy:v1.34-latest
    privileged: true
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    env_file:
      - .env
    ports:
      - ${ENVOY_PORT:-8080}:8080 # Expose Envoy's port to the host
    depends_on:
      - go_server
    networks:
      - grpc_net

networks:
  grpc_net:
    driver: bridge
